sudo: false

cache:
  directories:
    - node_modules
    - vendor

language:
    - php
    - node_js

php:
    - 7.0

services:
  - mysql

addons:
  hosts:
    - localhost

matrix:
  fast_finish: true
  include:
#     Run PHPCS against WPCS. I just picked to run it against 7.0.
    - php: 7.0
      env: PHPCS_BRANCH=master SNIFF=1
      addons:
        apt:
          packages:
            - libxml2-utils

node_js:
    - stable

env:
    global:
        - WP_MULTISITE=0

branches:
    only:
        - master
        - develop
        - /^release\/.*$/

before_install:
  - curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
  - chmod +x wp-cli.phar
  - sudo mv wp-cli.phar /usr/local/bin/wp
  - npm install

install:
  - /bin/bash custom-content/plugins/custom-plugin/bin/install-wp-tests.sh wordpress root '' 127.0.0.1
  - wp core download
  - wp config create --dbname=wordpress --dbuser=root
  - wp core install --url="http://localhost" --title="WP Test Site" --admin_user=admin --admin_password=admin --admin_email=foo@bar.com --skip-email
  - composer install --no-interaction

script:
  - vendor/bin/phpunit

after_script:
# deploy
