sudo: false

cache:
  directories:
    - node_modules
    - vendor
#    - $HOME/phpunit-bin

language:
    - php
    - node_js

php:
    - 7.0

matrix:
  fast_finish: true
  include:
    # Run PHPCS against WPCS. I just picked to run it against 7.0.
#    - php: 7.0
#      env: PHPCS_BRANCH=master SNIFF=1
#      addons:
#        apt:
#          packages:
#            - libxml2-utils

node_js:
    - stable

env:
    global:
        - WP_MULTISITE=0

branches:
    only:
        - master
        - develop
        - /^release\/.*$/

before_install:
    - apt-get update -yqq
    - apt-get install git -yqq
    - apt-get -yqqf install curl vim wget zip unzip rsync subversion gcc g++ make mysql-client libmcrypt-dev libmysqlclient-dev libpng-dev  --fix-missing
    - curl -sL https://deb.nodesource.com/setup_8.x | bash
    - curl -sL https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
    - echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
    - apt-get update -yqq
    - apt-get -yqqf install nodejs yarn
    # Install PHP extensions
    - docker-php-ext-install mysqli pdo_mysql mbstring
    # Install & enable Xdebug for code coverage reports
    - pecl install xdebug
    - docker-php-ext-enable mysqli pdo_mysql mbstring xdebug
    # Install and run Composer
    - curl -sS https://getcomposer.org/installer | php
    - php composer.phar install
    # Install WP Unit testing suite
    - bash install-wp-tests.sh wp_test root mysql mysql latest true

install:
    - source install-wp-tests.sh

script:

after_script:
    - sftp -o Port=2222 $USER@$HOST
