sudo: false

cache:
  directories:
    - node_modules
    - vendor
#    - $HOME/phpunit-bin

language:
    - php
    - node_js

php:
    - 7.0

services:
  - mysql

addons:
  hosts:
    - localhost

matrix:
  fast_finish: true
  include:
#     Run PHPCS against WPCS. I just picked to run it against 7.0.
    - php: 7.0
      env: PHPCS_BRANCH=master SNIFF=1
      addons:
        apt:
          packages:
            - libxml2-utils

node_js:
    - stable

env:
    global:
        - WP_MULTISITE=0

branches:
    only:
        - master
        - develop
        - /^release\/.*$/

before_install:
  - curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
  - chmod +x wp-cli.phar
  - sudo mv wp-cli.phar /usr/local/bin/wp
  - mysql -e 'CREATE DATABASE wordpress;'
  - /bin/bash custom-content/plugins/custom-plugin/bin/install-wp-tests.sh wordpress root

install:
# install wp
  - echo which wp

script:
# script

after_script:
# deploy
