sudo: false

cache:
  directories:
    - node_modules
    - vendor
    - $HOME/phpunit-bin

language:
    - php
    - node_js

php:
    - 7.0

matrix:
  fast_finish: true
  include:
    # Run PHPCS against WPCS. I just picked to run it against 7.0.
#    - php: 7.0
#      env: PHPCS_BRANCH=master SNIFF=1
#      addons:
#        apt:
#          packages:
#            - libxml2-utils

node_js:
    - stable

env:
    global:
        - WP_MULTISITE=0

branches:
    only:
        - master
        - develop
        - /^release\/.*$/

before_install:
#    - WP_VERSION=$( cat ./config/wp-version )
#    - echo "WP_VERSION=$WP_VERSION"

install:
#    - export DEV_LIB_PATH=dev-lib
#    - if [ ! -e "$DEV_LIB_PATH" ] && [ -L .travis.yml ]; then export DEV_LIB_PATH=$( dirname $( readlink .travis.yml ) ); fi
#    - if [ ! -e "$DEV_LIB_PATH" ]; then git clone https://github.com/xwp/wp-dev-lib.git $DEV_LIB_PATH; fi
#    - source $DEV_LIB_PATH/travis.install.sh

script:
#    - source $DEV_LIB_PATH/travis.script.sh
#    - if [ -e ./vendor/bin/phpmd ]; then ./vendor/bin/phpmd docroot/wp-content/plugins/beachbody-on-demand/src text docroot/wp-content/plugins/beachbody-on-demand/phpmd-ruleset.xml --exclude vendor --suffixes php; fi

after_script:
#    - source $DEV_LIB_PATH/travis.after_script.sh
