sudo: false

cache:
  directories:
    - node_modules
    - vendor
#    - $HOME/phpunit-bin

language:
    - php
    - node_js

php:
    - 7.0

matrix:
  fast_finish: true
  include:
#     Run PHPCS against WPCS. I just picked to run it against 7.0.
    - php: 7.0
      env: PHPCS_BRANCH=master SNIFF=1
      addons:
        apt:
          packages:
            - libxml2-utils

node_js:
    - stable

env:
    global:
        - WP_MULTISITE=0

branches:
    only:
        - master
        - develop
        - /^release\/.*$/

before_install:
# set up

install:
# install wp
  - echo which wp

script:
# script

after_script:
# deploy
