version: '3.3'

services:
   db:
     container_name: wpdb
     image: mysql:5.7
     restart: always
     ports:
       - 3306:3306
     environment:
       MYSQL_ROOT_PASSWORD: somewordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress

   wordpress:
     container_name: wp
     depends_on:
       - db
     links:
       - db
     image: wordpress:latest
     ports:
       - "8000:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
     volumes:
       - ./vendor:/var/www/html/vendor/
       - ./phpunit.xml.dist:/var/www/html/phpunit.xml.dist
       - ./phpunit-bootstrap.php:/var/www/html/phpunit-bootstrap.php
       - ./phpcs.xml:/var/www/html/phpcs.xml
       - ./phpmd-ruleset.xml:/var/www/html/phpmd-ruleset.xml
#       - ./wp-config.php:/var/www/html/wp-config.php



